<?php

namespace Database\Seeders;

use App\Models\Amendment;
use App\Models\Progress;
use App\Models\User;
use App\Models\Viability;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AmendmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $amendment = new Amendment(["parliamentary"=> "ARLETE SAMPAIO","amendment"=> "00455.01","caption"=> "OBRAS DE URBANIZAÇÃO NAS REGIÕES ADMINISTRATIVAS","work_program"=> "15.451.6209.1110.9971","nature_of_expense"=> "449051","price"=> "3100000","viability" => "",,"users_id" => User::pluck('id')->random()]);
        // $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'ARLETE SAMPAIO')->value('id'),"amendment"=> "00455.01","caption"=> "OBRAS DE URBANIZAÇÃO NAS REGIÕES ADMINISTRATIVAS","work_program"=> "15.451.6209.1110.9971","nature_of_expense"=> "449051","price"=> "3100000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'CHICO VIGILANTE')->value('id'),"amendment"=> "00345.01","caption"=> "EXECUÇÃO DE OBRAS DE INFRAESTRUTURA E URBANIZAÇÃO NO DISTRITO FEDERAL","work_program"=> "15.451.6209.1110.9967","nature_of_expense"=> "449051","price"=> "2703140","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'CHICO VIGILANTE')->value('id'),"amendment"=> "00346.01","caption"=> "REFORMA DE PARQUES E PRAÇAS PÚBLICAS NO DISTRITO FEDERAL","work_program"=> "15.451.6206.3902.9559","nature_of_expense"=> "449051","price"=> "2902000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'CLÁUDIO ABRANTES')->value('id'),"amendment"=> "00277.01","caption"=> "EXECUÇÃO DE OBRAS DE URBANIZAÇÃO EM TODO O DISTRITO FEDERAL","work_program"=> "15.451.6209.1110.9965","nature_of_expense"=> "449051","price"=> "3000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'CLÁUDIO ABRANTES')->value('id'),"amendment"=> "00279.01","caption"=> "CONSTRUÇÃO DE PRÉDIOS E PRÓPRIOS-ANEXO DO HOSPITAL DE PLANALTINA","work_program"=> "15.122.8206.1984.9878","nature_of_expense"=> "449051","price"=> "1000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'DANIEL DONIZET')->value('id'),"amendment"=> "00173.01","caption"=> "CONSTRUÇÃO DE PARCÃO","work_program"=> "15.451.6206.1950.9533","nature_of_expense"=> "449051","price"=> "300000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'DANIEL DONIZET')->value('id'),"amendment"=> "00174.01","caption"=> "REFORMA DE QUADRAS POLIESPORTIVAS","work_program"=> "15.451.6206.3048.9631","nature_of_expense"=> "339039","price"=> "600000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'DANIEL DONIZET')->value('id'),"amendment"=> "00192.01","caption"=> "CONSTRUÇÃO DE CAMPO SINTÉTICO - GAMA","work_program"=> "15.451.6206.1079.0036","nature_of_expense"=> "449051","price"=> "1500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'DELMASSO')->value('id'),"amendment"=> "00549.01","caption"=> "IMPLEMENTAÇÃO DA POLÍTICA PÚBLICA DE REVITALIZAÇÃO DAS QUADRAS RESIDENCIAIS NO DF - NOSSA QUADRA - LEI","work_program"=> "15.451.6209.9107.0145","nature_of_expense"=> "445042","price"=> "4200000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'EDUARDO PEDROSA')->value('id'),"amendment"=> "00151.01","caption"=> "REFORMA DE ESPAÇOS ESPORTIVOS EM PROL DE TODA COMUNIDADE DO DF","work_program"=> "15.451.6206.3048.9630","nature_of_expense"=> "339039","price"=> "1000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'EDUARDO PEDROSA')->value('id'),"amendment"=> "00152.01","caption"=> "CONSTRUÇÃO CAMPO DE FUTEBOL DE GRAMA SINTÉTICA EM PROL DE TODA COMUNIDADE DO DF","work_program"=> "15.451.6206.1079.0035","nature_of_expense"=> "449051","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'EDUARDO PEDROSA')->value('id'),"amendment"=> "00153.01","caption"=> "IMPLANTAÇÃO DE PONTO DE ENCONTRO COMUNITÁRIO - PEC EM PROL DE TODA COMUNIDADE DO DF","work_program"=> "15.812.6206.3596.8571","nature_of_expense"=> "449051","price"=> "300000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'EDUARDO PEDROSA')->value('id'),"amendment"=> "00154.01","caption"=> "REFORMA DE PRAÇAS PÚBLICAS E PARQUES EM PROL DE TODA COMUNIDADE DO DF","work_program"=> "15.451.6206.3902.9556","nature_of_expense"=> "339039","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'GUARDA JÂNIO')->value('id'),"amendment"=> "00081.01","caption"=> "URBANIZAÇÃO DA PRAÇA DO METRÔ NA CNN 02 DE CEILÂNDIA - RA IX","work_program"=> "15.451.6209.1110.9948","nature_of_expense"=> "449051","price"=> "200000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'GUARDA JÂNIO')->value('id'),"amendment"=> "00082.01","caption"=> "EXECUÇÃO DE OBRAS DE URBANIZAÇÃO NO DISTRITO FEDERAL","work_program"=> "15.451.6209.1110.9949","nature_of_expense"=> "449051","price"=> "1300000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'GUARDA JÂNIO')->value('id'),"amendment"=> "00093.01","caption"=> "IMPLANTAÇÃO DE PARQUES INFANTIL","work_program"=> "15.451.6206.3596.8568","nature_of_expense"=> "449051","price"=> "560000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'GUARDA JÂNIO')->value('id'),"amendment"=> "00094.01","caption"=> "CONSTRUÇÃO DE PISTA DE SKATE NA RA IX","work_program"=> "15.451.6206.1079.0034","nature_of_expense"=> "449051","price"=> "800000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'GUARDA JÂNIO')->value('id'),"amendment"=> "00095.01","caption"=> "MANUTENÇÃO DE CAMPO SINTÉTICO","work_program"=> "15.812.6206.4170.0011","nature_of_expense"=> "339039","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'HERMETO')->value('id'),"amendment"=> "00237.01","caption"=> "Cobertura da quadra h Poliesportiva do 4º BPM= Guará","work_program"=> "27.812.6206.3596.8572","nature_of_expense"=> "449051","price"=> "800000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'HERMETO')->value('id'),"amendment"=> "00239.01","caption"=> "Pavimentação Asfaltica h em todo o DF","work_program"=> "15.451.6209.1110.9960","nature_of_expense"=> "449051","price"=> "1800000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'IOLANDO')->value('id'),"amendment"=> "00113.01","caption"=> "INFRAESTRUTURA E URBANISMO i NAS Ras","work_program"=> "15.451.6209.1110.9953","nature_of_expense"=> "449051","price"=> "3000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JAQUELINE SILVA')->value('id'),"amendment"=> "00435.01","caption"=> "REFORMA DA FEIRA PERMANENTE DE SANTA MARIA - RA XIII","work_program"=> "15.451.6207.3247.9256","nature_of_expense"=> "449051","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JOÃO CARDOSO')->value('id'),"amendment"=> "00399.01","caption"=> "EXECUÇÃO DE OBRAS DE INFRAESTRUTURAS NO DISTRITO  FEDERAL","work_program"=> "15.451.6209.1110.9969","nature_of_expense"=> "449051","price"=> "1000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JOÃO CARDOSO')->value('id'),"amendment"=> "00400.01","caption"=> "REFORMA DAS FEIRAS PERMANENTES NO DISTRITO FEDERAL","work_program"=> "15.451.6207.3247.9255","nature_of_expense"=> "449051","price"=> "100000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JOÃO CARDOSO')->value('id'),"amendment"=> "00418.01","caption"=> "IMPLANTAÇÃO DE CRECHES EM ÁREA DO NÚCLEO RURAL PIPIRIPAU","work_program"=> "15.365.6221.3238.2735","nature_of_expense"=> "449051","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JOÃO CARDOSO')->value('id'),"amendment"=> "00420.01","caption"=> "REFORMA DE ESPAÇOS ESPORTIVOS","work_program"=> "27.812.6206.3048.9636","nature_of_expense"=> "449051","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JORGE VIANNA')->value('id'),"amendment"=> "00316.01","caption"=> "EXECUÇÃO DE OBRAS DE INFRAESTRUTURA E URBANISMO EM SAMAMBAIA - 2022","work_program"=> "15.451.6208.1110.9966","nature_of_expense"=> "449051","price"=> "1000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JORGE VIANNA')->value('id'),"amendment"=> "00525.01","caption"=> "REFORMA DE PARQUES INFANTIS NAS CIDADES DO DISTRITO FEDERAL","work_program"=> "15.451.6206.3902.9562","nature_of_expense"=> "449051","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JOSÉ GOMES')->value('id'),"amendment"=> "00327.01","caption"=> "CONSTRUÇÃO DE UNIDADE DA EDUCAÇÃO INFANTIL","work_program"=> "15.365.6221.3271.9372","nature_of_expense"=> "449051","price"=> "4000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JOSÉ GOMES')->value('id'),"amendment"=> "00328.01","caption"=> "REFORMA DE QUADRAS DE ESPORTES","work_program"=> "15.812.6206.3048.9634","nature_of_expense"=> "449051","price"=> "3768140","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JÚLIA LUCY')->value('id'),"amendment"=> "00248.01","caption"=> "Execução de Obras de Urbanização no Distrito Federal.","work_program"=> "15.451.6209.1110.9961","nature_of_expense"=> "449051","price"=> "2000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'JÚLIA LUCY')->value('id'),"amendment"=> "00275.01","caption"=> "Reforma de parques e praças públicos no Distrito Federal","work_program"=> "15.451.6206.3902.9557","nature_of_expense"=> "449051","price"=> "1970000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'LEANDRO GRASS')->value('id'),"amendment"=> "0035.01","caption"=> "EXECUÇÃO E RECUPERAÇÃO DE CALÇADAS NO PLANO PILOTO","work_program"=> "15.451.6209.1110.9947","nature_of_expense"=> "449051","price"=> "2300000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'LEANDRO GRASS')->value('id'),"amendment"=> "00032.01","caption"=> "CONSTRUÇÃO DE PONTOS DE ENCONTRO COMUNITÁRIO - PEC NO DISTRITO FEDERAL","work_program"=> "15.451.6206.3596.8566","nature_of_expense"=> "449051","price"=> "70000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'LEANDRO GRASS')->value('id'),"amendment"=> "00031.01","caption"=> "CONSTRUÇÃO DE PARQUES INFANTIS NO PLANO PILOTO","work_program"=> "15.451.6206.1950.9532","nature_of_expense"=> "449051","price"=> "200000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'LEANDRO GRASS')->value('id'),"amendment"=> "00033.01","caption"=> "CONSTRUÇÃO DE QUADRAS ESPORTIVAS NAS REGIÃO ADMINISTRATIVA DO PLANO PILOTO","work_program"=> "15.451.6206.1079.0033","nature_of_expense"=> "449051","price"=> "600000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'LEANDRO GRASS')->value('id'),"amendment"=> "00034.01","caption"=> "REFORMA DE QUADRAS DE ESPORTE NA REGIÃO ADMINISTRATIVA DO PLANO PILOTO","work_program"=> "15.451.6206.3048.9628","nature_of_expense"=> "339039","price"=> "360000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'MARTINS MACHADO')->value('id'),"amendment"=> "00375.01","caption"=> "EXECUÇÃO DE OBRAS E INFRAESTRUTURA NAS REGIÕES ADMINISTRATIVAS DO DISTRITO FEDERAL","work_program"=> "15.451.6209.1110.9968","nature_of_expense"=> "449051","price"=> "2000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'MARTINS MACHADO')->value('id'),"amendment"=> "00382.01","caption"=> "IMPLANTAÇÃO DE CAMPO DE GRAMA SINTÉTICA NO DISTRITO FEDERAL","work_program"=> "15.812.6206.1079.0038","nature_of_expense"=> "449051","price"=> "700000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'RAFAEL PRUDENTE')->value('id'),"amendment"=> "00570.01","caption"=> "IMPLANTAÇÃO DE INFRAESTRUTURA DE CICLOVIAS NAS REG. ADM. DO DF","work_program"=> "15.451.6216.3090.5335","nature_of_expense"=> "449051","price"=> "400000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'RAFAEL PRUDENTE')->value('id'),"amendment"=> "00551.01","caption"=> "CONSTRUÇÃO DE PRAÇAS PÚBLICAS E PARQUES--DISTRITO FEDERAL","work_program"=> "15.451.6206.1950.9535","nature_of_expense"=> "449051","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'RAFAEL PRUDENTE')->value('id'),"amendment"=> "00552.01","caption"=> "EXECUÇÃO DE OBRAS DE INFRAESTRUTURA E URBANIZAÇÃO NAS REG. ADM. DO DF","work_program"=> "15.451.6209.1110.9985","nature_of_expense"=> "449051","price"=> "1000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'RAFAEL PRUDENTE')->value('id'),"amendment"=> "00552.01","caption"=> "EXECUÇÃO DE OBRAS DE INFRAESTRUTURA E URBANIZAÇÃO NAS REG. ADM. DO DF","work_program"=> "15.451.6209.1110.9985","nature_of_expense"=> "339030","price"=> "1000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'RAFAEL PRUDENTE')->value('id'),"amendment"=> "00564.01","caption"=> "CONSTRUÇÃO DE ESPAÇOS ESPORTIVOS NAS REG. ADM. DO DF","work_program"=> "15.451.6206.1079.0041","nature_of_expense"=> "449051","price"=> "2000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'REGINALDO SARDINHA')->value('id'),"amendment"=> "00021.01","caption"=> "EXECUÇÃO DE OBRAS DE URBANIZAÇÃO EM TODO O DISTRITO FEDERAL","work_program"=> "15.451.6209.1110.9946","nature_of_expense"=> "449051","price"=> "5800000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'REGINALDO SARDINHA')->value('id'),"amendment"=> "00006.01","caption"=> "MANUTENÇÃO DE ESPAÇOS ESPORTIVOS, DESPORTIVOS E DE LAZER EM TODO O DF","work_program"=> "15.451.6206.3048.9627","nature_of_expense"=> "339039","price"=> "1500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'REGINALDO SARDINHA')->value('id'),"amendment"=> "00010.01","caption"=> "CONSTRUÇÃO DE PISTA DE SKATE - NA RA SUDOESTE/OCTOGONAL","work_program"=> "15.451.6206.1079.0032","nature_of_expense"=> "449051","price"=> "800000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'REGINALDO SARDINHA')->value('id'),"amendment"=> "00524.01","caption"=> "AQUISIÇÃO DE EQUIPAMENTOS PARA PARQUINHOS E PONTOS DE ENCONTRO COMUNITÁRIOS - PECS (EM 2022) - DISTRITO","work_program"=> "15.451.6206.3596.8573","nature_of_expense"=> "449052","price"=> "350000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'REGINALDO SARDINHA')->value('id'),"amendment"=> "00590.01","caption"=> "IMPLANTAÇÃO DE BASES DE CONCRETO PARA PONTOS DE ENCONTRO","work_program"=> "15.451.6206.3596.8576","nature_of_expense"=> "449051","price"=> "150000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'REGINALDO VERAS')->value('id'),"amendment"=> "00126.01","caption"=> "EXECUÇÃO DE OBRAS DE URBANIZAÇÃO","work_program"=> "15.451.6209.1110.9955","nature_of_expense"=> "449051","price"=> "1600000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'ROBÉRIO NEGREIROS')->value('id'),"amendment"=> "00211.01","caption"=> "OBRAS DE URBANIZAÇÃO EM TODO DISTRITO FEDERAL - 2022","work_program"=> "15.451.6209.1110.9959","nature_of_expense"=> "449051","price"=> "2753140","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'ROBÉRIO NEGREIROS')->value('id'),"amendment"=> "00212.01","caption"=> "MANUTENÇÃO DE ÁREAS AJARDINADAS EM TODO DISTRITO FEDERAL - 2022","work_program"=> "15.452.6209.8508.9229","nature_of_expense"=> "339039","price"=> "500000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'ROBÉRIO NEGREIROS')->value('id'),"amendment"=> "00213.01","caption"=> "CICLOVIA NO ALTIPLANO LESTE - 2022","work_program"=> "15.451.6216.3090.5331","nature_of_expense"=> "449051","price"=> "300000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'ROOSEVELT VILELA')->value('id'),"amendment"=> "00483.01","caption"=> "EXECUÇÃO DE OBRAS DE URBANIZAÇÃO","work_program"=> "15.451.6209.1110.9976","nature_of_expense"=> "449051","price"=> "7000000","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'ROOSEVELT VILELA')->value('id'),"amendment"=> "00486.01","caption"=> "MANUTENÇÃO DE ÁREAS URBANIZADAS E AJARDINADAS ","work_program"=> "15.452.6209.8508.9234","nature_of_expense"=> "339039","price"=> "1854140","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
        $amendment = new Amendment(["parliamentarians_id"=> DB::table('parliamentarians')->where('name', 'VALDELINO BARCELOS')->value('id'),"amendment"=> "00523.01","caption"=> "Execução de Obras de Urbanização e Infraestrutura no Distrito Federal","work_program"=> "15.451.6209.1110.9984","nature_of_expense"=> "449051","price"=> "7818140","viability_id" => Viability::pluck('id')->random(),"progress_id"=> Progress::pluck('id')->random(),"users_id" => User::pluck('id')->random()]); $amendment->save();
    }
}
